### ISSUE TITLE
The Roomba doesnt work

### ISSUE THREAD

**Issue by Baenker** [umesan/homebridge-roomba#4]
I think irobot change the url to control the roomba. Last week the url

https://irobot.axeda.com/services/v1/rest/Scripto/execute/AspenApiRequest?blid=xxxxx&robotpwd=xxxxpiw&method=getStatus

returns some infos. In the last days unfortunately no more.

**Comment by JensBonse** [comment]
I created a pull request to fix this issue.
iRobot added header validation.

**Comment by Baenker** [comment]
Update: I switched to 
[https://www.npmjs.com/package/homebridge-roomba980](url)

**Comment by umesan** [comment]
Thank you very much.
I upgraded it, so I will close this.
